image:
  source: hashicorp/http-echo:0.2.3
  pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "300m"
      memory: "150Mi"
    requests:
      cpu: "200m"
      memory: "100Mi"

ingress:
  fqdn:
  class: internal
  certSecretName:
  affinity: ''
enableMonitoring: false
