{{- if .Values.ingress.class }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-dump-server
  labels:
    app: simple-dump-server
    heritage: {{.Release.Service | quote}}
    release: {{.Release.Name | quote}}
    chart: {{ .Chart.Name }} 
spec:
  rules:
  - http:
      paths:
      - path: "/test"
        backend:
          service: 
            name: simple-dump-server
            port: 
              number: 8080
{{- end }}
